version: '3'
services:

  spring-boot-app:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  react-app:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: on-failure
