services:
  spring-boot-app:
    build:
      context: backend
    ports:
      - "8080:8080"
    network_mode: host

  react-app:
    build:
      context: frontend
    ports:
      - "3000:80"
    restart: on-failure
    network_mode: host
